Add documentation for ST7789-based displays
adafruit/Adafruit_CircuitPython_RGB_Display pull request #88
Opened 2021-01-04 21:55 UTC by agarthetiger

Hi, I've got an AdaFruit 1.3" TFT Bonnet with Joystick and am learning how to drive the display. I've had a bit of a learning curve with this and wanted to include the ST7789 module to the readthedocs site for this repo so that anyone else googling for information for this display might find these docs a bit quicker than I did :) 

I think I've made the right changes, I bumped the version number and build the docs locally which look fine in a browser on my machine (famous last words!). Apologies if I've missed anything or changed something I shouldn't. I'm happy to make any required modifications to this PR.

2021-01-04 22:16 UTC, ladyada requested changes

2021-01-04 22:16 UTC, ladyada commented on docs/conf.py
> +version = "3.10"
i think leave these two be (plz revert)

2021-01-04 22:16 UTC, ladyada commented on docs/conf.py
> +release = "3.10.2"
i think leave these two be (plz revert)

2021-01-04 22:50 UTC, agarthetiger commented on docs/conf.py
> +version = "3.10"
Sure thing, I've reverted these both.

2021-01-04 22:50 UTC, agarthetiger commented on docs/conf.py
> +release = "3.10.2"
Sure thing, I've reverted these both.

2021-01-04 23:59 UTC, ladyada approved these changes
nice!

2021-01-04 23:59 UTC, merged

2021-01-04 23:59 UTC, ladyada commented
looks good! lets see how it goes :)

2021-01-05 15:35 UTC, agarthetiger commented
Thank you! :)